// <auto-generated />
using System;
using Cinema.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema.Infrastructure.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    partial class CinemaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("MovieIdSequence")
                .HasMin(1L)
                .HasMax(100000L);

            modelBuilder.HasSequence<int>("SessionIdSequence")
                .HasMin(1L)
                .HasMax(100000L);

            modelBuilder.HasSequence<int>("TicketIdSequence")
                .HasMin(1L)
                .HasMax(100000L);

            modelBuilder.Entity("Cinema.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR MovieIdSequence");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movie", (string)null);

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            DurationMinutes = 169,
                            Genre = "Фантастика",
                            Title = "Интерстеллар"
                        },
                        new
                        {
                            MovieId = 2,
                            DurationMinutes = 175,
                            Genre = "Криминал",
                            Title = "Крестный отец"
                        },
                        new
                        {
                            MovieId = 3,
                            DurationMinutes = 142,
                            Genre = "Драма",
                            Title = "Побег из Шоушенка"
                        });
                });

            modelBuilder.Entity("Cinema.Domain.Entities.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR SessionIdSequence");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HallNumber")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("MovieId");

                    b.ToTable("Session", (string)null);

                    b.HasData(
                        new
                        {
                            SessionId = 1,
                            DateTime = new DateTime(2026, 1, 21, 18, 0, 0, 0, DateTimeKind.Local),
                            HallNumber = 1,
                            MovieId = 1
                        },
                        new
                        {
                            SessionId = 2,
                            DateTime = new DateTime(2026, 1, 21, 21, 30, 0, 0, DateTimeKind.Local),
                            HallNumber = 1,
                            MovieId = 1
                        },
                        new
                        {
                            SessionId = 3,
                            DateTime = new DateTime(2026, 1, 21, 19, 0, 0, 0, DateTimeKind.Local),
                            HallNumber = 2,
                            MovieId = 2
                        });
                });

            modelBuilder.Entity("Cinema.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR TicketIdSequence");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SeatType")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.HasIndex("SessionId");

                    b.ToTable("Ticket", (string)null);

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            IsAvailable = true,
                            Price = 600.00m,
                            RowNumber = 5,
                            SeatNumber = 10,
                            SeatType = 2,
                            SessionId = 1
                        },
                        new
                        {
                            TicketId = 2,
                            IsAvailable = false,
                            Price = 450.00m,
                            RowNumber = 5,
                            SeatNumber = 11,
                            SeatType = 0,
                            SessionId = 1
                        });
                });

            modelBuilder.Entity("Cinema.Domain.Entities.Session", b =>
                {
                    b.HasOne("Cinema.Domain.Entities.Movie", "Movie")
                        .WithMany("Sessions")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Cinema.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Cinema.Domain.Entities.Session", "Session")
                        .WithMany("Tickets")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Cinema.Domain.Entities.Movie", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Cinema.Domain.Entities.Session", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
